# Generated by Django 5.0.7 on 2024-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
    ]
