# Generated by Django 5.0.6 on 2024-06-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(verbose_name='дата и время последней попытки')),
                ('status', models.CharField(verbose_name='статус попытки (успешно / не успешно)')),
                ('answer', models.TextField(verbose_name='ответ почтового сервера, если он был')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылки',
            },
        ),
        migrations.CreateModel(
            name='MailService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф. И. О.')),
                ('email', models.CharField(max_length=100, verbose_name='Контактный email')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент сервиса',
                'verbose_name_plural': 'Клиенты сервиса',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_subject', models.CharField(blank=True, null=True, verbose_name='тема письма')),
                ('body', models.CharField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'Сообщение для рассылки',
                'verbose_name_plural': 'Сообщения для рассылки',
            },
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(verbose_name='дата и время первой отправки рассылки')),
                ('frequency', models.CharField(verbose_name='периодичность: раз в день, раз в неделю, раз в месяц')),
                ('status', models.CharField(verbose_name='статус рассылки (например, завершена, создана, запущена)')),
            ],
            options={
                'verbose_name': 'Рассылка (настройки)',
                'verbose_name_plural': 'Рассылки (настройки)',
            },
        ),
    ]
