# Generated by Django 5.0.6 on 2024-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0003_alter_newsletter_frequency_alter_newsletter_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='date_and_time',
            field=models.DateTimeField(verbose_name='дата и время первой отправки рассылки(дд.мм.гг)'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('СОЗДАНА', 'Создана'), ('ЗАПУЩЕНА', 'Запущена'), ('ЗАВЕРШЕНА', 'Завершена')], default='Создана', verbose_name='статус рассылки (например, завершена, создана, запущена)'),
        ),
    ]
