# Generated by Django 5.0.6 on 2024-07-20 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0004_alter_newsletter_date_and_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='customer',
            field=models.ManyToManyField(help_text='Укажите клиентов', to='mail_service.customer', verbose_name='Клиент сервиса'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_service.message', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='date_and_time',
            field=models.DateTimeField(verbose_name='Дата и время первой отправки рассылки(дд.мм.гг)'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'раз в день'), ('WEEKLY', 'раз в неделю'), ('MONTHLY', 'раз в месяц')], default=('daily',), verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('СОЗДАНА', 'Создана'), ('ЗАПУЩЕНА', 'Запущена'), ('ЗАВЕРШЕНА', 'Завершена')], default='Создана', verbose_name='Статус рассылки (например, завершена, создана, запущена)'),
        ),
    ]
