# Generated by Django 5.0.6 on 2024-07-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0005_newsletter_customer_newsletter_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='тело письма'),
        ),
        migrations.AlterField(
            model_name='message',
            name='letter_subject',
            field=models.TextField(blank=True, null=True, verbose_name='тема письма'),
        ),
    ]
