# Generated by Django 5.0.6 on 2024-07-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0006_alter_message_body_alter_message_letter_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='customer',
            field=models.ManyToManyField(to='mail_service.customer', verbose_name='Клиент сервиса'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('Раз в день', 'раз в день'), ('Раз в неделю', 'раз в неделю'), ('Раз в месяц', 'раз в месяц')], default=('daily',), verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', verbose_name='Статус рассылки (например, завершена, создана, запущена)'),
        ),
    ]
