# Generated by Django 5.0.7 on 2024-07-23 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0007_alter_newsletter_customer_alter_newsletter_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='mailing_parameters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_service.newsletter', verbose_name='параметры рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='name',
            field=models.CharField(blank=True, default='без названия', max_length=50, null=True, verbose_name='Название рассылки'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='customer',
            field=models.ManyToManyField(help_text='Укажите клиентов', to='mail_service.customer', verbose_name='Клиент сервиса'),
        ),
    ]
