# Generated by Django 5.0.7 on 2024-07-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0008_attempt_mailing_parameters_newsletter_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='status',
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='статус попытки (успешно / не успешно)'),
        ),
    ]
