# Generated by Django 5.0.7 on 2024-07-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0009_remove_attempt_status_attempt_is_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('can_delete_newsletter', 'Can delete newsletter'), ('can_view_newsletter', 'Can view newsletter'), ('can_delete_user', 'Can delete user'), ('can_view_user', 'Can view user')], 'verbose_name': 'Рассылка (настройки)', 'verbose_name_plural': 'Рассылки (настройки)'},
        ),
    ]
