# Generated by Django 5.0.7 on 2024-07-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0010_alter_newsletter_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='is_success',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='newsletter',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания рассылки'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время начала рассылки'),
        ),
    ]
