# Generated by Django 5.0.7 on 2024-07-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0011_rename_is_success_attempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='frequency',
            field=models.CharField(choices=[('MINUTLY', 'раз в минуту'), ('DAILY', 'раз в день'), ('WEEKLY', 'раз в неделю'), ('MONTHLY', 'раз в месяц')], default=('daily',), verbose_name='Периодичность: раз в день, раз в неделю, раз в месяц'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Создана'), ('STARTED', 'Запущена'), ('FINISHED', 'Завершена')], default='Создана', verbose_name='Статус рассылки (например, завершена, создана, запущена)'),
        ),
    ]
