# Generated by Django 5.0.7 on 2024-07-31 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0012_alter_newsletter_frequency_alter_newsletter_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Client',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='customer',
            new_name='client',
        ),
    ]
