# Generated by Django 5.0.7 on 2024-07-31 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0013_rename_customer_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='answer',
            new_name='server_response',
        ),
    ]
