# Generated by Django 5.0.7 on 2024-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0014_rename_answer_attempt_server_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.BooleanField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], verbose_name='статус попытки (успешно / не успешно)'),
        ),
    ]
