# Generated by Django 5.0.7 on 2024-07-31 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0015_alter_attempt_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='date_and_time',
            new_name='time',
        ),
    ]
