# Generated by Django 5.0.7 on 2024-07-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0016_rename_date_and_time_attempt_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='server_response',
            field=models.CharField(verbose_name='ответ почтового сервера, если он был'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], verbose_name='статус попытки (успешно / не успешно)'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail_service.message', verbose_name='Сообщение'),
        ),
    ]
