# Generated by Django 5.0.7 on 2024-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0017_alter_attempt_server_response_alter_attempt_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки'),
        ),
    ]
