# Generated by Django 5.0.7 on 2024-08-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_service', '0021_client_owner_message_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество клиентов рассылок'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество рассылок'),
        ),
    ]
